/**
 * MemoryRepairOutcomeRepository.ts — Persistent storage for repair outcome events
 *
 * Data layer for the memory_repair_outcomes table introduced in migration
 * 013_memory_repair_outcomes.sql.
 *
 * Design intent
 * ─────────────
 * This is a pure data-access layer — no business logic, no analytics, no
 * recommendations.  Consumers (MemoryRepairExecutionService,
 * MemoryRepairTriggerService) call append() after each significant event.
 * MemoryRepairAnalyticsService calls the query methods to read history.
 *
 * All queries use parameterised SQL.  No ORM.
 *
 * Node.js only — this file lives in electron/ and must not be imported by
 * the renderer.
 */

import { v4 as uuidv4 } from 'uuid';
import type { Pool } from 'pg';
import type {
    MemoryRepairOutcomeRecord,
    MemoryRepairOutcomeEventType,
} from '../../../shared/memory/MemoryRepairInsights';

// ---------------------------------------------------------------------------
// Input type for append()
// ---------------------------------------------------------------------------

/**
 * Everything required to insert one repair outcome row.
 * `id` and `createdAt` are generated by the repository.
 */
export type AppendRepairOutcomeInput = {
    eventType: MemoryRepairOutcomeEventType;
    severity?: 'info' | 'warning' | 'error' | 'critical' | null;
    reason?: string | null;
    state?: string | null;
    mode?: string | null;
    outcome?: 'recovered' | 'partial' | 'failed' | 'skipped' | null;
    actionType?: string | null;
    subsystem?: string | null;
    canonicalMemoryId?: string | null;
    cycleId?: string | null;
    detailsJson?: Record<string, unknown>;
    occurredAt?: string;
};

// ---------------------------------------------------------------------------
// Query result types (raw row shapes returned from analytics queries)
// ---------------------------------------------------------------------------

export type ReasonCountRow = {
    reason: string;
    cnt: number;
    first_at: string;
    last_at: string;
};

export type ActionOutcomeRow = {
    actionType: string;
    outcome: string | null;
    cnt: number;
};

export type OutcomeCountRow = {
    outcome: string | null;
    cnt: number;
};

export type DeadLetterBucketRow = {
    bucket: string;
    cnt: number;
};

export type StateTransitionRow = {
    fromState: string | null;
    toState: string | null;
    cnt: number;
};

// ---------------------------------------------------------------------------
// MemoryRepairOutcomeRepository
// ---------------------------------------------------------------------------

/**
 * Repository for the memory_repair_outcomes table.
 *
 * Usage:
 *   const repo = new MemoryRepairOutcomeRepository(pool);
 *   await repo.append({ eventType: 'repair_cycle', outcome: 'recovered', ... });
 *
 * All write failures are silently caught and logged — outcome persistence must
 * never interrupt or block the repair execution path.
 */
export class MemoryRepairOutcomeRepository {
    constructor(private readonly pool: Pool) {}

    // ── Write ────────────────────────────────────────────────────────────────

    /**
     * Insert a new repair outcome row.
     *
     * Silently returns null on DB error so callers in the repair hot-path are
     * never blocked by persistence failures.
     */
    async append(input: AppendRepairOutcomeInput): Promise<string | null> {
        const id = uuidv4();
        const occurredAt = input.occurredAt ?? new Date().toISOString();
        const detailsJson = JSON.stringify(input.detailsJson ?? {});

        try {
            await this.pool.query(
                `INSERT INTO memory_repair_outcomes
                   (id, event_type, severity, reason, state, mode, outcome,
                    action_type, subsystem, canonical_memory_id, cycle_id,
                    details_json, occurred_at)
                 VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13)`,
                [
                    id,
                    input.eventType,
                    input.severity ?? null,
                    input.reason ?? null,
                    input.state ?? null,
                    input.mode ?? null,
                    input.outcome ?? null,
                    input.actionType ?? null,
                    input.subsystem ?? null,
                    input.canonicalMemoryId ?? null,
                    input.cycleId ?? null,
                    detailsJson,
                    occurredAt,
                ],
            );
            return id;
        } catch (err) {
            console.error('[MemoryRepairOutcomeRepository] append failed:', err);
            return null;
        }
    }

    // ── Read: trigger/cycle counts ───────────────────────────────────────────

    /**
     * Count total repair triggers in the given window.
     */
    async countTriggers(windowSince: Date): Promise<number> {
        const result = await this.pool.query<{ cnt: string }>(
            `SELECT COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'repair_trigger'
               AND  occurred_at >= $1`,
            [windowSince.toISOString()],
        );
        return parseInt(result.rows[0]?.cnt ?? '0', 10);
    }

    /**
     * Count total repair cycles in the given window.
     */
    async countCycles(windowSince: Date): Promise<number> {
        const result = await this.pool.query<{ cnt: string }>(
            `SELECT COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'repair_cycle'
               AND  occurred_at >= $1`,
            [windowSince.toISOString()],
        );
        return parseInt(result.rows[0]?.cnt ?? '0', 10);
    }

    // ── Read: recurring failure analysis ────────────────────────────────────

    /**
     * Return counts of each failure reason in the window, ordered by
     * occurrence count descending.  Only reasons with at least minCount
     * occurrences are returned.
     */
    async getReasonCounts(windowSince: Date, minCount = 1): Promise<ReasonCountRow[]> {
        const result = await this.pool.query<{
            reason: string;
            cnt: string;
            first_at: Date;
            last_at: Date;
        }>(
            `SELECT reason,
                    COUNT(*) AS cnt,
                    MIN(occurred_at) AS first_at,
                    MAX(occurred_at) AS last_at
             FROM   memory_repair_outcomes
             WHERE  event_type IN ('repair_trigger', 'repair_cycle')
               AND  reason IS NOT NULL
               AND  occurred_at >= $1
             GROUP  BY reason
             HAVING COUNT(*) >= $2
             ORDER  BY cnt DESC, reason ASC`,
            [windowSince.toISOString(), minCount],
        );
        return result.rows.map(r => ({
            reason: r.reason,
            cnt: parseInt(r.cnt, 10),
            first_at: (r.first_at as unknown as Date).toISOString(),
            last_at: (r.last_at as unknown as Date).toISOString(),
        }));
    }

    // ── Read: action effectiveness ───────────────────────────────────────────

    /**
     * Return (actionType, outcome, count) aggregates for repair_action events
     * in the window.
     */
    async getActionOutcomeCounts(windowSince: Date): Promise<ActionOutcomeRow[]> {
        const result = await this.pool.query<{
            action_type: string;
            outcome: string | null;
            cnt: string;
        }>(
            `SELECT action_type,
                    outcome,
                    COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'repair_action'
               AND  action_type IS NOT NULL
               AND  occurred_at >= $1
             GROUP  BY action_type, outcome
             ORDER  BY action_type ASC, outcome ASC`,
            [windowSince.toISOString()],
        );
        return result.rows.map(r => ({
            actionType: r.action_type,
            outcome: r.outcome,
            cnt: parseInt(r.cnt, 10),
        }));
    }

    // ── Read: cycle outcomes ─────────────────────────────────────────────────

    /**
     * Return (outcome, count) aggregates for repair_cycle events in the window.
     */
    async getCycleOutcomeCounts(windowSince: Date): Promise<OutcomeCountRow[]> {
        const result = await this.pool.query<{ outcome: string | null; cnt: string }>(
            `SELECT outcome, COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'repair_cycle'
               AND  occurred_at >= $1
             GROUP  BY outcome
             ORDER  BY outcome ASC`,
            [windowSince.toISOString()],
        );
        return result.rows.map(r => ({
            outcome: r.outcome,
            cnt: parseInt(r.cnt, 10),
        }));
    }

    // ── Read: queue / dead-letter ────────────────────────────────────────────

    /**
     * Count deferred_replay events in the window, split by outcome.
     */
    async getReplayCounts(windowSince: Date): Promise<{ successes: number; failures: number }> {
        const result = await this.pool.query<{ outcome: string | null; cnt: string }>(
            `SELECT outcome, COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'deferred_replay'
               AND  occurred_at >= $1
             GROUP  BY outcome`,
            [windowSince.toISOString()],
        );
        let successes = 0;
        let failures = 0;
        for (const row of result.rows) {
            const cnt = parseInt(row.cnt, 10);
            if (row.outcome === 'recovered') successes += cnt;
            else failures += cnt;
        }
        return { successes, failures };
    }

    /**
     * Count dead_letter events in two equal halves of the window to detect growth.
     *
     * Returns `{ early, late }` where `early` is the count in the first half
     * and `late` in the second.  If `late > early`, the queue is growing.
     */
    async getDeadLetterHalves(windowSince: Date): Promise<{ early: number; late: number; total: number }> {
        const now = new Date();
        const mid = new Date((windowSince.getTime() + now.getTime()) / 2);

        const result = await this.pool.query<{ half: string; cnt: string }>(
            `SELECT CASE WHEN occurred_at < $2 THEN 'early' ELSE 'late' END AS half,
                    COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'dead_letter'
               AND  occurred_at >= $1
             GROUP  BY half`,
            [windowSince.toISOString(), mid.toISOString()],
        );
        let early = 0;
        let late = 0;
        for (const row of result.rows) {
            const cnt = parseInt(row.cnt, 10);
            if (row.half === 'early') early += cnt;
            else late += cnt;
        }
        return { early, late, total: early + late };
    }

    // ── Read: state trajectories ─────────────────────────────────────────────

    /**
     * Return health_transition rows in the window in chronological order.
     * Callers compute trajectory sequences from the ordered list.
     */
    async getHealthTransitions(windowSince: Date): Promise<Array<{ fromState: string | null; toState: string | null; occurredAt: string }>> {
        const result = await this.pool.query<{
            from_state: string | null;
            to_state: string | null;
            occurred_at: Date;
        }>(
            `SELECT
                 details_json->>'fromState' AS from_state,
                 state                       AS to_state,
                 occurred_at
             FROM   memory_repair_outcomes
             WHERE  event_type = 'health_transition'
               AND  occurred_at >= $1
             ORDER  BY occurred_at ASC`,
            [windowSince.toISOString()],
        );
        return result.rows.map(r => ({
            fromState: r.from_state,
            toState: r.to_state,
            occurredAt: (r.occurred_at as unknown as Date).toISOString(),
        }));
    }

    // ── Read: escalation scanning ────────────────────────────────────────────

    /**
     * Check whether the same failure reason occurred at least `threshold`
     * times within the window.  Returns matching reasons with their counts.
     */
    async getEscalationCandidateReasons(
        windowSince: Date,
        threshold: number,
    ): Promise<ReasonCountRow[]> {
        return this.getReasonCounts(windowSince, threshold);
    }

    /**
     * Count failed repair cycles (outcome='failed') in the window.
     */
    async countFailedCycles(windowSince: Date): Promise<number> {
        const result = await this.pool.query<{ cnt: string }>(
            `SELECT COUNT(*) AS cnt
             FROM   memory_repair_outcomes
             WHERE  event_type = 'repair_cycle'
               AND  outcome    = 'failed'
               AND  occurred_at >= $1`,
            [windowSince.toISOString()],
        );
        return parseInt(result.rows[0]?.cnt ?? '0', 10);
    }

    /**
     * Count how many consecutive hours the system spent in 'degraded' or
     * 'critical' state from the most recent health transitions.
     *
     * Returns duration in hours (0 if the system is currently healthy or
     * no transitions are recorded).
     */
    async getDegradedHours(windowSince: Date): Promise<number> {
        // Fetch the last transition OUT of a bad state (i.e. toState = 'healthy'/'reduced')
        // and the last transition INTO a bad state before that.
        const result = await this.pool.query<{ state: string | null; occurred_at: Date }>(
            `SELECT state, occurred_at
             FROM   memory_repair_outcomes
             WHERE  event_type = 'health_transition'
               AND  occurred_at >= $1
             ORDER  BY occurred_at DESC
             LIMIT  20`,
            [windowSince.toISOString()],
        );

        if (result.rows.length === 0) return 0;

        const BAD_STATES = new Set(['degraded', 'critical', 'disabled']);
        let badSince: Date | null = null;
        let recovered = false;

        for (const row of result.rows) {
            const state = row.state;
            const at = row.occurred_at as unknown as Date;
            if (!recovered && state && BAD_STATES.has(state)) {
                if (!badSince || at < badSince) badSince = at;
            } else if (state && !BAD_STATES.has(state)) {
                recovered = true;
                break;
            }
        }

        if (!badSince || recovered) return 0;

        const durationMs = Date.now() - badSince.getTime();
        return durationMs / 3_600_000;
    }

    // ── Read: full record retrieval (for testing/debug) ──────────────────────

    /**
     * Fetch raw outcome records in the given window, ordered by occurred_at.
     * Primarily used for testing and diagnostics.  Not called by analytics.
     */
    async listRecent(
        windowSince: Date,
        limit = 200,
    ): Promise<MemoryRepairOutcomeRecord[]> {
        const safeLimit = Math.max(1, Math.min(limit, 500));
        const result = await this.pool.query<Record<string, unknown>>(
            `SELECT *
             FROM   memory_repair_outcomes
             WHERE  occurred_at >= $1
             ORDER  BY occurred_at ASC
             LIMIT  $2`,
            [windowSince.toISOString(), safeLimit],
        );
        return result.rows.map(mapRow);
    }
}

// ---------------------------------------------------------------------------
// Internal row mapper
// ---------------------------------------------------------------------------

function mapRow(row: Record<string, unknown>): MemoryRepairOutcomeRecord {
    return {
        id: row.id as string,
        eventType: row.event_type as MemoryRepairOutcomeEventType,
        severity: (row.severity as MemoryRepairOutcomeRecord['severity']) ?? null,
        reason: (row.reason as string | null) ?? null,
        state: (row.state as string | null) ?? null,
        mode: (row.mode as string | null) ?? null,
        outcome: (row.outcome as MemoryRepairOutcomeRecord['outcome']) ?? null,
        actionType: (row.action_type as string | null) ?? null,
        subsystem: (row.subsystem as string | null) ?? null,
        canonicalMemoryId: (row.canonical_memory_id as string | null) ?? null,
        cycleId: (row.cycle_id as string | null) ?? null,
        detailsJson: (row.details_json as Record<string, unknown>) ?? {},
        occurredAt: (row.occurred_at as Date).toISOString(),
        createdAt: (row.created_at as Date).toISOString(),
    };
}
