import * as fs from 'fs';
import * as path from 'path';
import { ReflectionJournalEntry } from './reflectionEcosystemTypes';
import { ReflectionDataDirectories } from './DataDirectoryPaths';

export class ReflectionJournalService {
    private directories: ReflectionDataDirectories;

    constructor(directories: ReflectionDataDirectories) {
        this.directories = directories;
    }

    /**
     * PHASE 6: JOURNAL
     * Appends a detailed structured reflection entry.
     */
    public async writeEntry(entry: Omit<ReflectionJournalEntry, 'entryId' | 'timestamp'>): Promise<ReflectionJournalEntry> {
        const fullEntry: ReflectionJournalEntry = {
            entryId: `jour_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
            timestamp: new Date().toISOString(),
            ...entry
        };

        const jsonlPath = path.join(this.directories.journalDir, 'reflection-journal.jsonl');

        fs.appendFileSync(jsonlPath, JSON.stringify(fullEntry) + '\n', 'utf8');

        // Also generate an easy-to-read markdown summary if it's a major event
        if (['patch_staged', 'promotion_accepted', 'rollback_executed', 'validation_failed'].includes(entry.eventType)) {
            await this.writeMarkdownSummary(fullEntry);
        }

        return fullEntry;
    }

    private async writeMarkdownSummary(entry: ReflectionJournalEntry) {
        const safeIso = entry.timestamp.replace(/:/g, '-').replace(/\./g, '-');
        const mdPath = path.join(this.directories.journalDir, `summary_${safeIso}_${entry.eventType}.md`);

        const mdContent = `# Reflection Entry: ${entry.eventType}
**ID**: ${entry.entryId}
**Issue**: ${entry.issueId}
**Patch**: ${entry.patchId || 'N/A'}
**Timestamp**: ${entry.timestamp}
**Confidence**: ${entry.confidence}

## Summary
${entry.summary}

## Next Steps
${entry.nextSteps || 'None'}

## Tags
${entry.tags.join(', ')}

---
*Auto-generated by ReflectionJournalService*
`;
        fs.writeFileSync(mdPath, mdContent, 'utf8');
    }

    public async readRecentEntries(limit: number = 50): Promise<ReflectionJournalEntry[]> {
        const jsonlPath = path.join(this.directories.journalDir, 'reflection-journal.jsonl');
        if (!fs.existsSync(jsonlPath)) return [];

        const data = fs.readFileSync(jsonlPath, 'utf8');
        const lines = data.split('\n').filter(l => l.trim().length > 0);

        const entries: ReflectionJournalEntry[] = [];
        for (const line of lines) {
            try {
                entries.push(JSON.parse(line));
            } catch (e) { }
        }

        // Return latest first
        return entries.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()).slice(0, limit);
    }
}
