/**
 * MemoryRepairInsights.ts — Shared contracts for the repair-learning layer
 *
 * Types consumed by MemoryRepairOutcomeRepository, MemoryRepairAnalyticsService,
 * and MemoryRepairReflectionService.  Lives in shared/ so the renderer (e.g.
 * reflection dashboard) can import insight types without depending on the
 * Node.js-only data layer.
 *
 * All types are plain serialisable objects — no class instances, no functions.
 */

import type { MemorySubsystemState } from './MemoryHealthStatus';

// ---------------------------------------------------------------------------
// MemoryRepairOutcomeRecord — raw event persisted to the DB
// ---------------------------------------------------------------------------

/**
 * Discriminated union tag identifying the kind of repair event stored.
 */
export type MemoryRepairOutcomeEventType =
    | 'repair_trigger'
    | 'repair_cycle'
    | 'repair_action'
    | 'health_transition'
    | 'deferred_replay'
    | 'dead_letter';

/**
 * Single persisted event record in the memory_repair_outcomes table.
 *
 * Every significant repair-related lifecycle event maps to one row here so
 * the analytics layer can reconstruct history without relying on in-memory
 * state across restarts.
 */
export type MemoryRepairOutcomeRecord = {
    /** UUID v4. Generated by the repository. */
    id: string;
    /** Discriminator for the kind of event this row represents. */
    eventType: MemoryRepairOutcomeEventType;
    /** Severity of the associated trigger or transition. */
    severity?: 'info' | 'warning' | 'error' | 'critical' | null;
    /** Primary failure reason (maps to MemoryFailureReason). */
    reason?: string | null;
    /** Memory subsystem state at the time of the event. */
    state?: string | null;
    /** Resolved memory mode at the time of the event. */
    mode?: string | null;
    /**
     * Cycle / action outcome.  Only populated for repair_cycle and
     * repair_action eventTypes.
     */
    outcome?: 'recovered' | 'partial' | 'failed' | 'skipped' | null;
    /**
     * Repair action kind.  Only populated for repair_action eventTypes.
     * Maps to RepairActionKind in MemoryRepairExecutionService.
     */
    actionType?: string | null;
    /**
     * Subsystem associated with the event.  Used for aggregation by subsystem.
     * Examples: 'canonical', 'mem0', 'graph', 'rag', 'extraction', 'embedding'.
     */
    subsystem?: string | null;
    /**
     * Optional canonical memory ID — populated for deferred_replay and
     * dead_letter events when the event is associated with a specific record.
     */
    canonicalMemoryId?: string | null;
    /**
     * Optional repair cycle ID that this event belongs to.  Allows grouping
     * all events from a single cycle.
     */
    cycleId?: string | null;
    /** Arbitrary structured details as JSONB. Must not contain PII or raw content. */
    detailsJson: Record<string, unknown>;
    /** ISO-8601 UTC timestamp of when the event occurred (from the emitter). */
    occurredAt: string;
    /** ISO-8601 UTC timestamp of when the row was inserted (set by DB). */
    createdAt: string;
};

// ---------------------------------------------------------------------------
// Analytics output types
// ---------------------------------------------------------------------------

/**
 * Summary of a subsystem that has failed repeatedly within the analysis window.
 */
export type RecurringFailure = {
    /** The failure reason (e.g. 'mem0_unavailable'). */
    reason: string;
    /** Human-readable subsystem label. */
    subsystem: string;
    /** Total occurrences of this reason in the window. */
    occurrenceCount: number;
    /** Timestamp of the first occurrence in the window. */
    firstSeenAt: string;
    /** Timestamp of the most recent occurrence. */
    lastSeenAt: string;
    /**
     * True when the system recovered after each trigger (i.e. restarts work
     * but keep being needed) — indicates instability rather than permanent
     * failure.
     */
    recoversBetweenFailures: boolean;
};

/**
 * Effectiveness metrics for a single repair action kind.
 */
export type ActionEffectivenessEntry = {
    /** The action kind (e.g. 'reconnect_mem0'). */
    actionType: string;
    /** Total times this action was executed in the window. */
    totalExecutions: number;
    /** Times the action returned success=true. */
    successCount: number;
    /** Times the action returned success=false or threw. */
    failureCount: number;
    /** Times the action was skipped (no handler / max_attempts). */
    skipCount: number;
    /** Success rate as a fraction [0, 1]. */
    successRate: number;
};

/**
 * Summary of deferred-work queue / dead-letter behaviour over the window.
 */
export type QueueBehaviorSummary = {
    /** Total deferred_replay events in the window. */
    totalReplays: number;
    /** Successful replay events. */
    replaySuccesses: number;
    /** Failed replay events. */
    replayFailures: number;
    /** Items that entered the dead-letter state in the window. */
    deadLetterCount: number;
    /**
     * True when the dead-letter count is growing (more recent half of the
     * window has more dead-letters than the earlier half).
     */
    deadLetterGrowing: boolean;
};

/**
 * A pattern that warrants escalation to higher-priority logging or planning.
 */
export type EscalationCandidate = {
    /** Machine-readable code for the escalation type. */
    code:
        | 'repeated_failure_reason'      // same reason N times in M hours
        | 'repeated_cycle_failure'       // repair cycle outcome=failed N times
        | 'prolonged_degraded'           // system stuck degraded/critical > T hours
        | 'growing_dead_letter_queue'    // dead-letter items increasing
        | 'strict_mode_repeatedly_blocked'; // strict mode blocking too frequently
    /** Human-readable explanation tied to concrete counts/timestamps. */
    description: string;
    /** Evidence supporting the escalation (counts, timestamps). */
    evidence: Record<string, unknown>;
    /** ISO-8601 timestamp of first evidence in this escalation window. */
    firstEvidenceAt: string;
    /** ISO-8601 timestamp of most recent evidence. */
    lastEvidenceAt: string;
};

/**
 * A state-transition trajectory observed across the window.
 */
export type RepairTrajectory = {
    /** Ordered sequence of states visited (e.g. ['healthy','degraded','recovered']). */
    stateSequence: MemorySubsystemState[];
    /** Number of times this trajectory pattern occurred. */
    occurrenceCount: number;
    /** True if this trajectory ended with a successful recovery. */
    endsHealthy: boolean;
};

// ---------------------------------------------------------------------------
// MemoryRepairInsightSummary — top-level output of the analytics pass
// ---------------------------------------------------------------------------

/**
 * Structured summary produced by MemoryRepairAnalyticsService for a given
 * time window.  Consumed by MemoryRepairReflectionService to generate
 * actionable recommendations.
 *
 * Same window + same data always produces the same summary (deterministic).
 */
export type MemoryRepairInsightSummary = {
    /** Analysis window in hours. */
    windowHours: number;
    /** ISO-8601 UTC timestamp when this summary was generated. */
    generatedAt: string;
    /** Total repair cycles found in the window. */
    totalCycles: number;
    /** Total repair triggers found in the window. */
    totalTriggers: number;
    /** Subsystems / failure reasons that recur within the window. */
    recurrentFailures: RecurringFailure[];
    /** Per-action effectiveness statistics. */
    actionEffectiveness: ActionEffectivenessEntry[];
    /** Queue / backlog health summary. */
    queueBehavior: QueueBehaviorSummary;
    /** Patterns that may warrant escalation or self-maintenance action. */
    escalationCandidates: EscalationCandidate[];
    /** State trajectories observed across cycles. */
    trajectories: RepairTrajectory[];
};

// ---------------------------------------------------------------------------
// MemoryRepairRecommendation — output of the reflection service
// ---------------------------------------------------------------------------

/**
 * A concrete, explainable recommendation produced by MemoryRepairReflectionService.
 *
 * Each recommendation is tied to evidence from the insight summary so it can
 * be audited by humans and consumed deterministically by future planners.
 */
export type MemoryRepairRecommendation = {
    /** Machine-readable code for the recommendation type. */
    code:
        | 'investigate_subsystem'      // persistent failure of a subsystem
        | 'review_repair_action'       // low-effectiveness repair action
        | 'drain_dead_letter_queue'    // dead-letter queue needs attention
        | 'extend_analysis_window'     // insufficient data in current window
        | 'escalate_to_maintenance'    // serious pattern requiring human review
        | 'monitor_trajectory';        // concerning but not yet critical trajectory
    /** Human-readable recommendation text. */
    description: string;
    /** Priority level for consumers. */
    priority: 'low' | 'medium' | 'high' | 'critical';
    /**
     * Structured evidence that produced this recommendation.  Must contain
     * concrete counts, timestamps, and/or identifiers — no vague assertions.
     */
    evidence: Record<string, unknown>;
    /** ISO-8601 timestamp of recommendation generation. */
    generatedAt: string;
};

/**
 * Complete output of MemoryRepairReflectionService for one analysis pass.
 */
export type MemoryRepairReflectionReport = {
    /** ISO-8601 UTC timestamp of this report. */
    generatedAt: string;
    /** The insight summary this report was derived from. */
    summary: MemoryRepairInsightSummary;
    /** Ordered list of recommendations (highest priority first). */
    recommendations: MemoryRepairRecommendation[];
    /**
     * True when the report contains at least one critical recommendation
     * that should be surfaced immediately.
     */
    hasCriticalFindings: boolean;
};
