
/**
 * Represents a single message in a conversation history.
 * 
 * Used as input to all brain implementations. The conversation is modeled
 * as an ordered array of ChatMessages with alternating roles.
 */
export interface ChatMessage {
    /**
     * The role of the message author.
     * - `'system'` — System instructions (injected by AgentService).
     * - `'user'` — User input.
     * - `'assistant'` — AI-generated response.
     * - `'tool'` — Tool execution result.
     */
    role: 'system' | 'user' | 'assistant' | 'tool';
    /** The text content of the message. */
    content: string;
    /**
     * Optional array of base64-encoded images attached to the message.
     * Supported by Ollama's multimodal models (e.g., LLaVA).
     */
    images?: string[];
    /** Tool calls generated by the assistant (for 'assistant' role). */
    tool_calls?: ToolCall[];
    /** ID of the tool call this message responds to (for 'tool' role). */
    tool_call_id?: string;
    /** Name of the tool (fallback for legacy or strict servers). */
    name?: string;
    /** Optional metadata (e.g., token usage, timestamp) */
    metadata?: any;
}

/**
 * Represents a call to a specific tool/function requested by the LLM.
 */
export interface ToolCall {
    /** Unique identifier for the tool call instance. */
    id: string;
    /** The type of call (currently only 'function' is supported). */
    type: 'function';
    /** The function definition and arguments provided by the model. */
    function: {
        /** The name of the function to execute. */
        name: string;
        /** 
         * The arguments for the function. 
         * Can be a JSON object (if already parsed) or a raw string. 
         */
        arguments: any;
    };
    /** Support for model-specific extensions (e.g., Gemini's thought_signature) */
    [key: string]: any;
}

/**
 * Represents the response from a brain (LLM) after processing a conversation.
 * 
 * Contains the generated text and optional metadata about the inference
 * (model name, token usage, completion status).
 */
export interface BrainResponse {
    /** The generated text response from the model. */
    content: string;
    /** Tool calls requested by the model. */
    toolCalls?: ToolCall[];
    /** Optional inference metadata (token usage, model name, completion status). */
    metadata?: {
        usage?: {
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
        };
        [key: string]: any;
    };
}

export interface BrainOptions {
    /** 
     * Optional abort signal. 
     * Note: streamResponse has its own signal param for backwards compat, 
     * but options.signal is preferred where possible. 
     */
    signal?: AbortSignal;
    /** Max tokens to generate. */
    maxTokens?: number;
    /** Temperature (0-2). */
    temperature?: number;
    /** Timeout in milliseconds. */
    timeout?: number;
    /** 
     * Optional tool choice constraint. 
     * - 'auto': model decides (default)
     * - 'required': model MUST call at least one tool
     * - 'none': model must NOT call any tools
     */
    tool_choice?: 'auto' | 'required' | 'none';
    /** 
     * Optional prompt audit record for telemetry and debugging. 
     */
    auditRecord?: any;
    /** Any other model-specific options. */
    [key: string]: any;
}

/**
 * IBrain — Abstract interface for all LLM inference backends.
 */
export interface IBrain {
    /**
     * Unique identifier for this brain instance.
     */
    id: string;

    /**
     * Re-configures the brain's internal settings (e.g., after model reconciliation).
     */
    configure(baseUrl: string, model: string): void;

    /**
     * Checks whether the brain's inference server is reachable.
     */
    ping(): Promise<boolean>;

    /**
     * Sends a conversation to the brain and returns the complete response.
     */
    generateResponse(messages: ChatMessage[], systemPrompt?: string, tools?: any[], options?: BrainOptions): Promise<BrainResponse>;

    /**
     * Sends a conversation to the brain and streams the response token by token.
     */
    streamResponse(
        messages: ChatMessage[],
        systemPrompt: string,
        onChunk: (chunk: string) => void,
        signal?: AbortSignal,
        tools?: any[],
        options?: BrainOptions
    ): Promise<BrainResponse>;
}
